eks_cluster_version                        = "1.30"
karpenter_chart_version                    = "1.0.0"
aws_load_balancer_controller_chart_version = "1.8.2"
metrics_server_chart_version               = "3.12.1"
external_dns_chart_version                 = "1.14.5"
ingress_nginx_chart_version                = "4.11.1"
