eks_cluster_version                        = "1.32"
karpenter_chart_version                    = "1.4.0"
aws_load_balancer_controller_chart_version = "1.13.2"
external_dns_chart_version                 = "1.16.1"
ingress_nginx_chart_version                = "4.12.2"
gitlab_chart_version                       = "8.3.0"
argocd_chart_version                       = "7.4.4"