eks_cluster_version                        = "1.32"
karpenter_chart_version                    = "1.4.0"
aws_load_balancer_controller_chart_version = "1.13.2"
external_dns_chart_version                 = "1.16.1"
ingress_nginx_chart_version                = "4.12.2"
gitlab_chart_version                       = "9.0.0"
argocd_chart_version                       = "8.0.6"
kube_prometheus_stack_chart_version        = "61.9.0"
thanos_chart_version                       = "15.7.20"

alert_slack_channel     = "infra"
alert_slack_webhook_url = "aHR0cHM6Ly9ob29rcy5zbGFjay5jb20vc2VydmljZXMvVDAxVkRDNjNBQUcvQjA3QU1DVzFTMkYvVmljZVRoNGZ0UDVXOWRyWHRGSjNtVlVh"